freebsd_instance:
    image: freebsd-11-2-release-amd64

task:
    install_script: pkg install -y rust gmake asciidoc pkgconf stfl curl json-c ncurses openssl sqlite3 gettext-tools
    script: RUST_BACKTRACE=1 gmake
