freebsd_task:
    freebsd_instance:
        matrix:
            - image: freebsd-11-2-release-amd64
            - image: freebsd-12-0-release-amd64
    install_script: pkg install -y rust gmake asciidoc pkgconf stfl curl json-c ncurses openssl sqlite3 gettext-tools
    compile_script: RUST_BACKTRACE=1 gmake all test
    test_script: cargo test
