freebsd_task:
    freebsd_instance:
        matrix:
            - image: freebsd-11-2-release-amd64
            - image: freebsd-12-0-release-amd64
        cpu: 8
        memory: 8G

    install_script: pkg install -y rust gmake asciidoc pkgconf stfl curl json-c ncurses openssl sqlite3 gettext-tools
    # CI builds take a while to provision, install dependencies and compile our
    # stuff. To maximize the benefits, we ask Make to process as many rules as
    # possible before failing. This enables developers to fix more errors before
    # re-submitting the code to CI, which should increase throughput.
    compile_script: RUST_BACKTRACE=1 gmake --jobs=9 --keep-going all test
    test_script: cargo test
