[package]
name = "libnewsboat"
version = "2.14.0"
authors = ["Alexander Batischev <eual.jp@gmail.com>"]

[dependencies]
chrono = "0.4"
rand = "0.5"
once_cell = "0.1.6"
regex = "1.0"
url = "1.7"
dirs = "1.0.4"
# At least 0.3.13 doesn't work with 1.25:
# https://travis-ci.org/newsboat/newsboat/jobs/468075104#L1032
# https://travis-ci.org/newsboat/newsboat/jobs/468075114#L2803
# I simply rolled back to 0.3.9, which did work.
backtrace = "= 0.3.9"

[dev-dependencies]
tempfile = "3"
