[package]
name = "libnewsboat"
version = "2.14.0"
authors = ["Alexander Batischev <eual.jp@gmail.com>"]

[dependencies]
chrono = "0.4"
rand = "0.5"
once_cell = "0.1.6"
regex = "1.0"
url = "1.7"

[dev-dependencies]
tempfile = "3"
